package main

import (
	"encoding/json"
	"fmt"
	"os"
	"runtime"
	"time"
)

const configFileName = "bnm.json"

// schemaURL is the published JSON Schema for bnm.json, written into
// configs generated by `bnm init` so editors can validate and autocomplete.
const schemaURL = "https://raw.githubusercontent.com/Yarnadori/bnm/main/schema/bnm.schema.json"

type Config struct {
	Schema      string                 `json:"$schema,omitempty"`
	Name        string                 `json:"name,omitempty"`
	Version     string                 `json:"version,omitempty"`
	Directories map[string]Directory   `json:"directories,omitempty"`
	Scripts     map[string]ScriptGroup `json:"scripts"`
}

type ScriptGroup struct {
	Mode        string   `json:"mode,omitempty"`
	DependsOn   []string `json:"dependsOn,omitempty"`
	MaxParallel int      `json:"maxParallel,omitempty"`
	Tasks       []Task   `json:"tasks"`
}

type Directory struct {
	Alias string `json:"alias"`
	Path  string `json:"path"`
}

type Task struct {
	Name    string            `json:"-"`
	LogPath string            `json:"-"`
	Dir     string            `json:"dir,omitempty"`
	Command Command           `json:"command"`
	Env     map[string]string `json:"env,omitempty"`
	Timeout Duration          `json:"timeout,omitempty"`
	Retries int               `json:"retries,omitempty"`
}

// Duration is a time.Duration that unmarshals from a JSON string like "30s".
type Duration time.Duration

func (d *Duration) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("timeout must be a duration string like \"30s\"")
	}
	v, err := time.ParseDuration(s)
	if err != nil {
		return fmt.Errorf("invalid timeout %q (expected a duration like \"30s\" or \"2m\")", s)
	}
	*d = Duration(v)
	return nil
}

func (d Duration) String() string {
	return time.Duration(d).String()
}

type Command string

func (c *Command) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		*c = Command(s)
		return nil
	}

	var m map[string]string
	if err := json.Unmarshal(data, &m); err == nil {
		osName := runtime.GOOS
		if cmd, ok := m[osName]; ok {
			*c = Command(cmd)
		} else if osName == "darwin" && m["mac"] != "" {
			*c = Command(m["mac"])
		} else if m["default"] != "" {
			*c = Command(m["default"])
		} else {
			*c = ""
		}
		return nil
	}

	return fmt.Errorf("command must be a string or an object mapping OS names to strings")
}

func (c Command) String() string {
	return string(c)
}

// loadConfig reads and parses bnm.json in the current directory
func loadConfig() (*Config, error) {
	data, err := os.ReadFile(configFileName)
	if err != nil {
		return nil, fmt.Errorf("%s not found. Please initialize the project with 'bnm init'", configFileName)
	}

	var config Config
	if err := json.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("failed to parse %s: %w", configFileName, err)
	}

	for name, group := range config.Scripts {
		if group.Mode != "" && group.Mode != "parallel" && group.Mode != "sequential" {
			return nil, fmt.Errorf("script '%s' has unknown mode '%s' (expected \"parallel\" or \"sequential\")", name, group.Mode)
		}
		if group.MaxParallel < 0 {
			return nil, fmt.Errorf("script '%s' has negative maxParallel %d", name, group.MaxParallel)
		}
		for i, task := range group.Tasks {
			if task.Timeout < 0 {
				return nil, fmt.Errorf("script '%s' task %d has negative timeout %s", name, i+1, task.Timeout)
			}
			if task.Retries < 0 {
				return nil, fmt.Errorf("script '%s' task %d has negative retries %d", name, i+1, task.Retries)
			}
		}
	}

	if err := validateDependencies(&config); err != nil {
		return nil, err
	}

	return &config, nil
}

// validateDependencies checks that every dependsOn entry references an
// existing script and that the dependency graph has no cycles.
func validateDependencies(config *Config) error {
	const (
		visiting = 1
		done     = 2
	)
	state := map[string]int{}

	var visit func(name string) error
	visit = func(name string) error {
		switch state[name] {
		case visiting:
			return fmt.Errorf("dependency cycle detected involving script '%s'", name)
		case done:
			return nil
		}
		state[name] = visiting
		for _, dep := range config.Scripts[name].DependsOn {
			if _, ok := config.Scripts[dep]; !ok {
				return fmt.Errorf("script '%s' depends on unknown script '%s'", name, dep)
			}
			if err := visit(dep); err != nil {
				return err
			}
		}
		state[name] = done
		return nil
	}

	for name := range config.Scripts {
		if err := visit(name); err != nil {
			return err
		}
	}
	return nil
}

// mustLoadConfig loads bnm.json or exits with an error message
func mustLoadConfig() *Config {
	config, err := loadConfig()
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}
	return config
}
