package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"runtime"
	"strings"
	"time"
)

const configFileName = "bnm.json"

// schemaURL is the published JSON Schema for bnm.json, written into
// configs generated by `bnm init` so editors can validate and autocomplete.
const schemaURL = "https://raw.githubusercontent.com/Yarnadori/bnm/main/schema/bnm.schema.json"

type Config struct {
	Schema      string                 `json:"$schema,omitempty"`
	Name        string                 `json:"name,omitempty"`
	Version     string                 `json:"version,omitempty"`
	Directories map[string]Directory   `json:"directories,omitempty"`
	Scripts     map[string]ScriptGroup `json:"scripts"`
}

// Directory is a named directory entry. In JSON it is written as a plain
// path string; the legacy {"alias": ..., "path": ...} object form is still
// accepted, and its alias works as an alternative name.
type Directory struct {
	Alias string
	Path  string
}

func (d *Directory) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		d.Path = s
		return nil
	}
	var obj struct {
		Alias string `json:"alias"`
		Path  string `json:"path"`
	}
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("directory must be a path string or an object with \"path\"")
	}
	d.Alias, d.Path = obj.Alias, obj.Path
	return nil
}

func (d Directory) MarshalJSON() ([]byte, error) {
	if d.Alias == "" {
		return json.Marshal(d.Path)
	}
	return json.Marshal(struct {
		Alias string `json:"alias"`
		Path  string `json:"path"`
	}{d.Alias, d.Path})
}

// ScriptGroup is one runnable script. In JSON it takes three forms:
//
//	"test": "npm test"                            — run in every directory
//	"dev": {"frontend": "npm run dev", ...}       — name-to-command map; the
//	                                                key doubles as the
//	                                                directory unless the value
//	                                                sets "dir"
//	"dev": {"mode": ..., "tasks": ...}            — detailed form; tasks is
//	                                                a name-keyed object or
//	                                                the legacy array
type ScriptGroup struct {
	Mode        string
	DependsOn   []string
	MaxParallel int
	Watch       bool // watch by default; only honored for the target script
	Tasks       []Task
	AllCommand  Command // run-everywhere shorthand, expanded by loadConfig
}

// scriptGroupFields are the keys of the detailed form. An object containing
// "tasks" is detailed; anything else is a task map. A task in the map form
// cannot use one of these names; the detailed "tasks" object has no such
// restriction.
var scriptGroupFields = map[string]bool{"mode": true, "dependsOn": true, "maxParallel": true, "watch": true, "tasks": true}

func (g *ScriptGroup) UnmarshalJSON(data []byte) error {
	trimmed := bytes.TrimSpace(data)
	if len(trimmed) > 0 && trimmed[0] == '"' {
		var s string
		if err := json.Unmarshal(data, &s); err != nil {
			return err
		}
		// An empty command would silently expand to zero tasks
		if strings.TrimSpace(s) == "" {
			return fmt.Errorf("script command must not be empty")
		}
		g.AllCommand = Command(s)
		return nil
	}
	if string(trimmed) == "null" {
		return fmt.Errorf("script must not be null")
	}

	var probe map[string]json.RawMessage
	if err := json.Unmarshal(data, &probe); err != nil {
		return fmt.Errorf("script must be a command string, a directory-to-command object, or an object with \"tasks\"")
	}

	if rawTasks, ok := probe["tasks"]; ok {
		for key := range probe {
			if !scriptGroupFields[key] {
				return fmt.Errorf("unknown script field %q", key)
			}
		}
		var d struct {
			Mode        string   `json:"mode"`
			DependsOn   []string `json:"dependsOn"`
			MaxParallel int      `json:"maxParallel"`
			Watch       bool     `json:"watch"`
		}
		if err := json.Unmarshal(data, &d); err != nil {
			return err
		}
		g.Mode, g.DependsOn, g.MaxParallel, g.Watch = d.Mode, d.DependsOn, d.MaxParallel, d.Watch
		tasks, err := unmarshalTasks(rawTasks)
		if err != nil {
			return err
		}
		g.Tasks = tasks
		return nil
	}

	for _, key := range []string{"mode", "dependsOn", "maxParallel"} {
		if _, ok := probe[key]; ok {
			return fmt.Errorf("script field %q requires a \"tasks\" entry", key)
		}
	}
	// A task named "watch" stays valid in the map form, but a boolean can
	// only be the script field, so catch it with a pointed error instead of
	// a command-type complaint.
	if raw, ok := probe["watch"]; ok {
		if v := string(bytes.TrimSpace(raw)); v == "true" || v == "false" {
			return fmt.Errorf("script field \"watch\" requires a \"tasks\" entry")
		}
	}
	tasks, err := decodeTaskMap(data)
	if err != nil {
		return err
	}
	g.Tasks = tasks
	return nil
}

func (g ScriptGroup) MarshalJSON() ([]byte, error) {
	if g.AllCommand != "" {
		return json.Marshal(g.AllCommand.String())
	}
	rawTasks, keys, ok := taskMapJSON(g.Tasks)
	if ok && g.Mode == "" && len(g.DependsOn) == 0 && g.MaxParallel == 0 && !g.Watch && len(g.Tasks) > 0 {
		reserved := false
		for _, key := range keys {
			if scriptGroupFields[key] {
				reserved = true
				break
			}
		}
		if !reserved {
			return rawTasks, nil
		}
	}
	if !ok {
		// Legacy array fallback; explicit task names (if any) are lost here,
		// which only happens for task lists the map form cannot represent.
		var err error
		if rawTasks, err = json.Marshal(g.Tasks); err != nil {
			return nil, err
		}
	}
	return json.Marshal(struct {
		Mode        string          `json:"mode,omitempty"`
		DependsOn   []string        `json:"dependsOn,omitempty"`
		MaxParallel int             `json:"maxParallel,omitempty"`
		Watch       bool            `json:"watch,omitempty"`
		Tasks       json.RawMessage `json:"tasks"`
	}{g.Mode, g.DependsOn, g.MaxParallel, g.Watch, rawTasks})
}

// taskMapJSON renders tasks as a name-keyed object, preserving order, and
// returns the keys used. It reports ok=false when that form would lose or
// change information on reload: an empty command or a duplicate key.
func taskMapJSON(tasks []Task) (json.RawMessage, []string, bool) {
	var buf bytes.Buffer
	buf.WriteByte('{')
	keys := make([]string, 0, len(tasks))
	seen := map[string]bool{}
	for i, t := range tasks {
		if t.Dir == "" {
			t.Dir = "."
		}
		key := t.Name
		if key == "" {
			key = t.Dir
		}
		if t.Command == "" || seen[key] {
			return nil, nil, false
		}
		seen[key] = true
		keys = append(keys, key)

		var value any = t.Command.String()
		if len(t.Env) > 0 || t.Timeout != 0 || t.Retries != 0 || t.Watch || t.Dir != key {
			value = t // Dir is normalized above, so a named task keeps its directory
		}
		keyJSON, err := json.Marshal(key)
		if err != nil {
			return nil, nil, false
		}
		valueJSON, err := json.Marshal(value)
		if err != nil {
			return nil, nil, false
		}
		if i > 0 {
			buf.WriteByte(',')
		}
		buf.Write(keyJSON)
		buf.WriteByte(':')
		buf.Write(valueJSON)
	}
	buf.WriteByte('}')
	return buf.Bytes(), keys, true
}

// unmarshalTasks parses the "tasks" field: a name-keyed object, or the
// legacy array of task objects with a "dir" field.
func unmarshalTasks(data []byte) ([]Task, error) {
	trimmed := bytes.TrimSpace(data)
	switch {
	case len(trimmed) > 0 && trimmed[0] == '[':
		var tasks []Task
		if err := json.Unmarshal(data, &tasks); err != nil {
			return nil, err
		}
		return tasks, nil
	case len(trimmed) > 0 && trimmed[0] == '{':
		return decodeTaskMap(data)
	default:
		return nil, fmt.Errorf("\"tasks\" must be a name-keyed object or an array of tasks")
	}
}

// decodeTaskMap parses a name-keyed object into tasks, preserving the
// order keys appear in the file (encoding/json maps would lose it, and the
// order is meaningful in sequential mode).
func decodeTaskMap(data []byte) ([]Task, error) {
	dec := json.NewDecoder(bytes.NewReader(data))
	if _, err := dec.Token(); err != nil {
		return nil, err
	}
	var tasks []Task
	seen := map[string]bool{}
	for dec.More() {
		keyTok, err := dec.Token()
		if err != nil {
			return nil, err
		}
		name, _ := keyTok.(string)
		if strings.TrimSpace(name) == "" {
			return nil, fmt.Errorf("task name must not be empty")
		}
		if seen[name] {
			return nil, fmt.Errorf("duplicate task name %q", name)
		}
		seen[name] = true
		var raw json.RawMessage
		if err := dec.Decode(&raw); err != nil {
			return nil, err
		}
		task, err := taskFromValue(name, raw)
		if err != nil {
			return nil, err
		}
		tasks = append(tasks, task)
	}
	return tasks, nil
}

// taskFromValue builds a task from a name-keyed entry. The value is a
// command (string or OS object), or a task object — recognized by its
// "command" field — carrying dir/env/timeout/retries. The key names the
// task; unless the object sets "dir", it doubles as the directory.
func taskFromValue(name string, raw []byte) (Task, error) {
	task := Task{Name: name, Dir: name}
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) > 0 && trimmed[0] == '{' {
		var probe map[string]json.RawMessage
		if err := json.Unmarshal(raw, &probe); err != nil {
			return task, err
		}
		if _, ok := probe["command"]; ok {
			var t Task
			if err := json.Unmarshal(raw, &t); err != nil {
				return task, err
			}
			t.Name = name
			if t.Dir == "" {
				t.Dir = name
			}
			return t, nil
		}
	}
	if err := json.Unmarshal(raw, &task.Command); err != nil {
		return task, err
	}
	return task, nil
}

type Task struct {
	Name     string            `json:"-"`
	LogPath  string            `json:"-"`
	DirLabel string            `json:"-"` // the dir as written in the config; set by resolveTask
	Dir      string            `json:"dir,omitempty"`
	Command  Command           `json:"command"`
	Env      map[string]string `json:"env,omitempty"`
	Timeout  Duration          `json:"timeout,omitempty"`
	Retries  int               `json:"retries,omitempty"`
	Watch    bool              `json:"watch,omitempty"` // restart just this task when its directory changes
}

// Duration is a time.Duration that unmarshals from a JSON string like "30s".
type Duration time.Duration

func (d *Duration) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("timeout must be a duration string like \"30s\"")
	}
	v, err := time.ParseDuration(s)
	if err != nil {
		return fmt.Errorf("invalid timeout %q (expected a duration like \"30s\" or \"2m\")", s)
	}
	*d = Duration(v)
	return nil
}

func (d Duration) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.String())
}

func (d Duration) String() string {
	return time.Duration(d).String()
}

type Command string

func (c *Command) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		*c = Command(s)
		return nil
	}

	var m map[string]string
	if err := json.Unmarshal(data, &m); err == nil {
		osName := runtime.GOOS
		if cmd, ok := m[osName]; ok {
			*c = Command(cmd)
		} else if osName == "darwin" && m["mac"] != "" {
			*c = Command(m["mac"])
		} else if m["default"] != "" {
			*c = Command(m["default"])
		} else {
			*c = ""
		}
		return nil
	}

	return fmt.Errorf("command must be a string or an object mapping OS names to strings")
}

func (c Command) String() string {
	return string(c)
}

// loadConfig reads and parses bnm.json in the current directory
func loadConfig() (*Config, error) {
	data, err := os.ReadFile(configFileName)
	if err != nil {
		return nil, fmt.Errorf("%s not found. Please initialize the project with 'bnm init'", configFileName)
	}

	var config Config
	if err := json.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("failed to parse %s: %w", configFileName, err)
	}

	for key, dir := range config.Directories {
		if strings.TrimSpace(dir.Path) == "" {
			return nil, fmt.Errorf("directory '%s' has no path", key)
		}
	}

	for name, group := range config.Scripts {
		// Expand the run-everywhere shorthand into one task per directory
		if group.AllCommand != "" {
			if len(config.Directories) == 0 {
				return nil, fmt.Errorf("script '%s' runs in every directory, but no directories are configured", name)
			}
			for _, key := range sortedKeys(config.Directories) {
				group.Tasks = append(group.Tasks, Task{Name: key, Dir: key, Command: group.AllCommand})
			}
			config.Scripts[name] = group
		}

		if group.Mode != "" && group.Mode != "parallel" && group.Mode != "sequential" {
			return nil, fmt.Errorf("script '%s' has unknown mode '%s' (expected \"parallel\" or \"sequential\")", name, group.Mode)
		}
		if group.MaxParallel < 0 {
			return nil, fmt.Errorf("script '%s' has negative maxParallel %d", name, group.MaxParallel)
		}
		for i, task := range group.Tasks {
			if task.Timeout < 0 {
				return nil, fmt.Errorf("script '%s' task %d has negative timeout %s", name, i+1, task.Timeout)
			}
			if task.Retries < 0 {
				return nil, fmt.Errorf("script '%s' task %d has negative retries %d", name, i+1, task.Retries)
			}
			// Restarting individual tasks contradicts a fixed execution order
			if task.Watch && group.Mode == "sequential" {
				return nil, fmt.Errorf("script '%s' task %d has \"watch\": true, which requires parallel mode", name, i+1)
			}
		}
	}

	if err := validateDependencies(&config); err != nil {
		return nil, err
	}

	return &config, nil
}

// validateDependencies checks that every dependsOn entry references an
// existing script and that the dependency graph has no cycles.
func validateDependencies(config *Config) error {
	const (
		visiting = 1
		done     = 2
	)
	state := map[string]int{}

	var visit func(name string) error
	visit = func(name string) error {
		switch state[name] {
		case visiting:
			return fmt.Errorf("dependency cycle detected involving script '%s'", name)
		case done:
			return nil
		}
		state[name] = visiting
		for _, dep := range config.Scripts[name].DependsOn {
			if _, ok := config.Scripts[dep]; !ok {
				return fmt.Errorf("script '%s' depends on unknown script '%s'", name, dep)
			}
			if err := visit(dep); err != nil {
				return err
			}
		}
		state[name] = done
		return nil
	}

	for name := range config.Scripts {
		if err := visit(name); err != nil {
			return err
		}
	}
	return nil
}

// mustLoadConfig loads bnm.json or exits with an error message
func mustLoadConfig() *Config {
	config, err := loadConfig()
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}
	return config
}
